import logging

from ..const import DEFAULT_THRESHOLD, PKG_NAME

_LOGGER = logging.getLogger(PKG_NAME)


def main(
    input: str,
    metadata: str,
    universe: str,
    output: str,
    labels: str,
    files: str,
    threshold: float = DEFAULT_THRESHOLD,
):
    """
    Main function for the distance pipeline

    :param input: Path to input file generated by preprocess
    :param metadata: Path to metadata file
    :param universe: Path to universe file
    :param output: Path to output folder
    :param labels: Labels string (cell_type,target)
    :param files: Path to files to be embedded (the data)
    :param threshold: Threshold for filtering
    """
    _LOGGER.info("Running distances...")

    # PLACE CODE FOR RUNNING DISTANCES HERE
