import logging
import os
import subprocess


from ..const import (DEFAULT_DIM, DEFAULT_LEARNING_RATE, DEFAULT_NUM_EPOCHS,
                     PKG_NAME)

_LOGGER = logging.getLogger(PKG_NAME)


def main(
    path_to_starsapce: str,
    input: str,
    output: str,
    num_epochs: str = DEFAULT_NUM_EPOCHS,
    dim: str = DEFAULT_DIM,
    learning_rate: str = DEFAULT_LEARNING_RATE,
):
    """
    Train a starspace model.

    :param path_to_starsapce: Path to starspace folder (must be prebuilt)
    :param input: Path to input file generated by preprocess
    :param num_epochs: Number of epochs
    :param dim: Dimension of embeddings
    :param learning_rate: Learning rate
    :param output: Path to output folder
    """
    _LOGGER.info("Running training...")

    # PLACE TRAINING CODE HERE
    
    
    n_process = 8
    label_prefix = "__label__"

    model = os.path.join(output, "starspace_trained_model")
    path_to_starsapce = os.path.join(path_to_starsapce, 'starspace')


    print(type(input))

    
    if os.path.exists(model):
        subprocess.Popen(
            [
                path_to_starsapce,
                "train",
                "-trainFile",
                input,
                "-model",
                model,
                "-initModel",
                model,
                "-trainMode",
                "0",
                "-dim",
                dim,
                "-epoch",
                num_epochs,
                "-negSearchLimit",
                "5",
                "-thread",
                "20",
                "-lr",
                learning_rate,
            ]
        )
    else:
        subprocess.Popen(
            [
                path_to_starsapce,
                "train",
                "-trainFile",
                input,
                "-model",
                model,
                "-trainMode",
                "0",
                "-dim",
                dim,
                "-epoch",
                num_epochs,
                "-negSearchLimit",
                "5",
                "-thread",
                "20",
                "-lr",
                learning_rate,
            ]
        )

    print("Train bedembed done.")

