import logging

from ..const import (DEFAULT_DIM, DEFAULT_LEARNING_RATE, DEFAULT_NUM_EPOCHS,
                     PKG_NAME)

_LOGGER = logging.getLogger(PKG_NAME)


def main(
    path_to_starsapce: str,
    input: str,
    output: str,
    num_epochs: int = DEFAULT_NUM_EPOCHS,
    dim: str = DEFAULT_DIM,
    learning_rate: float = DEFAULT_LEARNING_RATE,
):
    """
    Train a starspace model.

    :param path_to_starsapce: Path to starspace folder (must be prebuilt)
    :param input: Path to input file generated by preprocess
    :param num_epochs: Number of epochs
    :param dim: Dimension of embeddings
    :param learning_rate: Learning rate
    :param output: Path to output folder
    """
    _LOGGER.info("Running training...")

    # PLACE TRAINING CODE HERE
