def main(
    path_to_starsapce: str,
    input: str,
    num_epochs: int,
    dim: str,
    learning_rate: float,
    output: str,
):
    """
    Train a starspace model.

    :param path_to_starsapce: Path to starspace folder (must be prebuilt)
    :param input: Path to input file generated by preprocess
    :param num_epochs: Number of epochs
    :param dim: Dimension of embeddings
    :param learning_rate: Learning rate
    :param output: Path to output folder
    """
    # train the model :D
