site_name: gitk
site_logo: img/gitk_logo.svg
site_url: http://gitk.databio.org/
repo_url: http://github.com/databio/gitk
pypi_name: gitk

nav:
  - Getting Started: 
    - Introduction: README.md
  - How-to guides:    
    - Create consensus peaks: likelihood/consensus-peaks.md
  - Reference:
    - API: autodoc_build/gitk.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      jupyter_source: "docs_jupyter"
      jupyter_build: "docs_jupyter/build"
      autodoc_package: "gitk"
      no_top_level: true
  - search
