site_name: gitk
site_logo: img/gitk_logo.svg
site_url: http://gitk.databio.org/
repo_url: http://github.com/databio/gitk
pypi_name: gitk

nav:
  - Getting Started: 
    - Introduction: README.md
    - Module overviews: modules.md
  - How-to guides:    
    - Assess universe fit: tutorials/assess-universe.md
    - Search intervals with BEDSpace: tutorials/bedspace.md
    - Evaluate embeddings: tutorials/evaluation.md
    - Train region2vec embeddings: tutorials/region2vec.md
    - Train single-cell embeddings: tutorials/train-scembed-model.md
    - Tokenize a BED file: tutorials/tokenization.md
    - Build universe: tutorials/build-universe.md
    - Create consensus peaks: tutorials/create-consensus-peaks.md
  - Reference:
    - API: autodoc_build/gitk.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      jupyter_source: "docs_jupyter"
      jupyter_build: "docs_jupyter/build"
      autodoc_package: "gitk"
      no_top_level: false
  - search
