site_name: geniml
site_logo: img/geniml_logo.svg
site_url: http://geniml.databio.org/
repo_url: http://github.com/databio/geniml
pypi_name: geniml
papers: https://www.biorxiv.org/content/10.1101/2020.11.02.364145v1

nav:
  - Getting Started: 
    - Introduction: README.md
    - Module overviews: modules.md
  - How-to guides:    
    - Assess universe fit: tutorials/assess-universe.md
    - Search intervals with BEDSpace: tutorials/bedspace.md
    - Evaluate embeddings: tutorials/evaluation.md
    - Train region2vec embeddings: tutorials/region2vec.md
    - Train single-cell embeddings: tutorials/train-scembed-model.md
    - Load vector database with embeddings: tutorials/load-qdrant-with-cell-embeddings.md
    - Cell-type prediction using KNN: tutorials/cell-type-annotation-with-knn.md
    - Tokenization: tutorials/tokenization.md
    - Tokenize a BED file on the command line: tutorials/cli-tokenization.md
    - Create consensus peaks: tutorials/create-consensus-peaks.md
    - Fine-tune embeddings: tutorials/fine-tune-region2vec-model.md
    - Randomize bed files: tutorials/bedshift.md
    - Create evaluation dataset with bedshift: tutorials/bedshift-evaluation-guide.md
  - Reference:
    - API: autodoc_build/geniml.md
    - Support: support.md
    - Contributing: contributing.md
    - Changelog: changelog.md

theme: databio

plugins:
  - databio:
      autodoc_build: "docs/autodoc_build"
      jupyter_source: "docs_jupyter"
      jupyter_build: "docs_jupyter/build"
      # autodoc_package: "geniml"
      no_top_level: false
  - search


navbar:
  right:
  - text: Manuscripts
    icon: fa-file-alt
    href: manuscripts