MODULE_NAME = "region2vec"
MAX_WAIT_TIME = 10800

DEFAULT_EPOCHS = 100
DEFAULT_GENSIM_EPOCHS = 1
DEFAULT_MIN_COUNT = 10
DEFAULT_N_SHUFFLES = 1  # 1 is sufficient for most cases
DEFAULT_WINDOW_SIZE = 5
DEFAULT_EMBEDDING_SIZE = 100
DEFAULT_EPOCHS = 10
DEFAULT_INIT_LR = 0.1  # https://github.com/databio/gitk/issues/6#issuecomment-1476273162
DEFAULT_MIN_LR = 0.0001  # gensim default
DEFAULT_DECAY_RATE = 0.95
DEFAULT_HIDDEN_DIM = 100
DEFAULT_BATCH_SIZE = 32
DEFAULT_CHECKPOINT_FILE_NAME = "checkpoint.pt"
DEFAULT_UNIVERSE_FILE_NAME = "universe.bed"

MODEL_FILE_NAME = "model.bin"
UNIVERSE_FILE_NAME = "universe.bed"
