name: Run pytests for dev

on:
  pull_request:
    branches: [dev]

jobs:

  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Hack setup-python cache

        if: hashFiles('**/requirements.txt', '**/pyproject.toml') == ''
        run: |
          touch ./requirements.txt

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'  # caching can speed up the workflow by reusing the installed dependencies

      - name: Install test dependencies
        run: if [ -f requirements/requirements-test.txt ]; then pip install -r requirements/requirements-test.txt; fi

      - name: Install test dependencies
        run: if [ -f requirements/requirements-ml.txt ]; then pip install -r requirements/requirements-test.txt; fi

      - name: Install package
        run: python -m pip install .

      - name: Run pytest tests
        run: pytest tests -x -vv --remote-data
